### ISSUE TITLE
add seed file 

### ISSUE THREAD

**Issue by loudmouse** [loudmouse/water_tanks#36]
- sample addresses
- sample photos

**Comment by iorme1** [comment]
I have 12 sample Chicago water tank photos/addresses that I can incorporate into the seed file but I'll wait to hear back from you guys before sending anymore PR's due to the previous conflicts in my last 2.

**Comment by loudmouse** [comment]
@iorme1 hey man sorry for the delay to get back to you. I'll get with @jalletto and we'll review your PR's and get back to you with feedback. We're a bit slow moving but are excited you found our project. We'll be in touch.
