### ISSUE TITLE
add delete

### ISSUE THREAD

**Issue by loudmouse** [loudmouse/water_tanks#37]
- ability to delete a photo - only the photo owner can delete his/her photos
- ability to delete a tank location (only admin can approve a location delete)
- ability for user to flag a tank location that no longer exists

**Comment by iorme1** [comment]
Hi, i came across this project through issuehub.io and would love to start tackling these issues.  I sent a PR for the first part of this issue "ability to delete a photo - only the photo owner can delete his/her photo".  I would like to work on the second part now as well:  "ability to delete a tank location (only admin can approve a location delete)".   However, I don't know if I have enough information here on how you would like this to be implemented. I didn't see any user roles set up in this application yet, so I'm unsure about how to deal with the admin-approval part of this feature.  A little guidance about how this should look would be much appreciated! I look forward to working on more issues for this project if you don't mind me helping. Thanks!

**Comment by iorme1** [comment]
Hey, I sent another PR recently, however, I'm noticing that i'm getting some conflicts.  I may have overstepped a bit, I'm still new to helping out with open source. I'll hold off on the PR's for now until I hear back from you. That way, if you don't mind me contributing, I can just wait to see what you guys would want to delegate to me.
