### ISSUE TITLE
Error messages are no longer visible on sign-in/sign-up

### ISSUE THREAD

**Issue by jalletto** [loudmouse/water_tanks#58]
The error messages are in black on a gray background. Need to change font color to white.

**Comment by jalletto** [comment]
If you try to sign up with an email that already exists you should see what I'm talking about. You'll see "1 Error has prevented this user from being created" or some shit. Then below that is a list of the errors, but those are in black and you can barely see them.

**Comment by loudmouse** [comment]
Ah-ha! I gotcha. I'll fix it right up.

**Comment by jalletto** [comment]
Thanks dude! I tried but I have no idea whats going on with that css haha

**Comment by loudmouse** [comment]
No worries. I can fix it. 

When I get back in town I'd be happy to spend some more time on the styles with you to explain what's going on. I know we'd meant to do it the other weekend but didn't spend as much time with it as we probably should have.
